esphome:
  name: sqmmetertest
  friendly_name: TSL2591 Lux Sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR_KEY"

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.1.105
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-9Baa98"
    password: "NIB1I1IEanZ6"

captive_portal:
    
web_server:
  port: 80

i2c:
  sda: 21
  scl: 22

sensor:
  - platform: tsl2591
    name: "TSL2591 - Light Level"
    id: "TSL2591"
    address: 0x29
    update_interval: 60s
    gain: auto
    device_factor: 53
    integration_time: 600ms
    glass_attenuation_factor: 14.4
    visible:
      name: "TSL2591 visible light"
    infrared:
      name: "TSL2591 infrared light"
    full_spectrum:
      name: "TSL2591 full spectrum light"
    calculated_lux:
      id: lux
      name: "TSL2591 Lux"
      accuracy_decimals: 1

    actual_gain:
      id: "actual_gain"
      name: "TSL2591 actual gain"

  - platform: template
    name: "TSL2591 Calculated SQM"
    id: Calculated_sqm
    lambda: |-
      return (log10(id(lux).state/108000)/-0.4);
    unit_of_measurement: "mag/arcsec2"

      
